### PR TITLE
Tick tock game

### PR DESCRIPTION
**Pull request by J-o-s-h-u-a**
Probably we don't need this stuff in the master branch, but for now it doesn't hurt and can help us as reference or test loop. For example we could link one of our buttons on the title screen to open the tic tac toe game instead of options until we implement the option loop.

### CODE REVIEW

**Comment by ofyildiz** [comment]
> Probably we don't need this stuff in the master branch, but for now it doesn't hurt and can help us as reference or test loop. For example we could link one of our buttons on the title screen to open the tic tac toe game instead of options until we implement the option loop.

Great idea, in the future we might even add a 'debug - mode' into our game where could call up tic tac toe & and other things that we don't want in the real game, but that would be interesting for debugging and testing purposes.

**Review by ofyildiz — CHANGES_REQUESTED** [review]
Please add a comment to remind us that these gitignores are specific to the tic tac toe game, and not necessary for the main game.

**Review by J-o-s-h-u-a — COMMENTED** [review]
I reviewed the changes ?! - There were non or I didnt see them...

**Review by ofyildiz — APPROVED** [review]
Looks good!

**Pull request merged**
